<?php
if (!defined('ABSPATH')) exit;

/**
 * Cross-franchise puzzle batch (40 puzzles), authored 2026-09-07.
 *
 * The existing pool is strong but franchise-deep: roughly a quarter of its
 * puzzles draw three or four of their categories from a single IP, so on those
 * days a player outside that fandom cannot get a foothold at all. Scheduling
 * now spaces those days apart, but spacing does not change the mix.
 *
 * Every puzzle here is solvable from general gaming literacy rather than
 * knowledge of one series: currencies, save points, netcode, storefronts,
 * accessibility settings, the vocabulary of patch notes. The wordplay category
 * in each is the gold tier, following the pattern of the strongest existing
 * puzzles ('Super ___', '___ Screen').
 *
 * NOT yet in rotation: tag_connections_get_puzzle_pool() does not merge this
 * file until the batch has been reviewed. See the note at the bottom.
 */
function tag_connections_get_puzzle_pool_batch2() {
    return [
        // ===== Small Change =====
        [
            'title' => 'Small Change',
            'items' => [
                ['id' => 1, 'text' => 'Rings', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Studs', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Bolts', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Zenny', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Estus', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Medkit', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Phoenix Down', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Bandage', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Bonfire', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Bench', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Typewriter', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Campfire', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'You Died', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Wasted', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Game Over', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Mission Failed', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Currencies You Grind For', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Healing Items', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Places You Save', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => 'On-Screen Death Messages', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Party Composition =====
        [
            'title' => 'Party Composition',
            'items' => [
                ['id' => 1, 'text' => 'Tank', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Healer', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Support', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Damage', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Common', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Rare', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Epic', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Legendary', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'FPS', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'RPG', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'DLC', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'NPC', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Roguelike', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Soulslike', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Metroidvania', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Battle Royale', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Multiplayer Roles', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Loot Rarities', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Gaming Acronyms', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => 'Genres Named For One Game', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Live Update =====
        [
            'title' => 'Live Update',
            'items' => [
                ['id' => 1, 'text' => 'Game Pass', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'PS Plus', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Switch Online', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Ubisoft+', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Easy', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Normal', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Hard', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Nightmare', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Any%', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Glitchless', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Splits', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'RTA', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Nerf', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Buff', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Rework', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Revert', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Subscription Services', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Difficulty Labels', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Speedrun Terms', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => 'What A Patch Can Do', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Mount Up =====
        [
            'title' => 'Mount Up',
            'items' => [
                ['id' => 1, 'text' => 'Chocobo', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Roach', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Torrent', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Epona', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Tails', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Daxter', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Dogmeat', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Palico', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Nuka-Cola', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Butterbeer', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Perk-a-Cola', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Moonshine', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Brain', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Sand', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Fire', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Snow', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Rideable Companions', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Animal Sidekicks', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Fictional Drinks', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Storm', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Gather Materials =====
        [
            'title' => 'Gather Materials',
            'items' => [
                ['id' => 1, 'text' => 'Iron', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Leather', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Cloth', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Wood', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Hunger', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Thirst', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Stamina', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Warmth', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Rain', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Fog', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Snow', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Storm', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'War', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Mine', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Star', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Witch', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Crafting Materials', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Survival Meters', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Weather You Play In', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Craft', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== The Long Load =====
        [
            'title' => 'The Long Load',
            'items' => [
                ['id' => 1, 'text' => 'Tip', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Lore', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Spinner', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Progress Bar', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Continue', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Options', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Credits', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Quit', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Slot', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Autosave', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Checkpoint', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Overwrite', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Rate', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Drop', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Buffer', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Time', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Loading Screen Staples', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Pause Menu Options', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Save File Words', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => 'Frame ___', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Boss Arena =====
        [
            'title' => 'Boss Arena',
            'items' => [
                ['id' => 1, 'text' => 'Fog Gate', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Health Bar', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Arena', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Phase Two', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Grunt', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Elite', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Miniboss', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Swarm', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Poison', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Burn', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Freeze', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Stun', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Boss', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Gold', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Adrenaline', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Speed', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Boss Fight Furniture', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Enemy Tiers', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Status Effects', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Rush', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Shopkeepers =====
        [
            'title' => 'Shopkeepers',
            'items' => [
                ['id' => 1, 'text' => 'Blacksmith', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Alchemist', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Fence', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Peddler', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Farmer', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Miner', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Fisher', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Cook', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Buy', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Sell', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Haggle', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Barter', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Save', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Spawn', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Fast Travel', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Skill', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Merchant Archetypes', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'In-Game Jobs', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Trading Verbs', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Point', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Controller Layout =====
        [
            'title' => 'Controller Layout',
            'items' => [
                ['id' => 1, 'text' => 'Start', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Select', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Home', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Share', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Bumper', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Trigger', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Paddle', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Grip', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Drift', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Deadzone', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Flick', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Overshoot', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Haptic', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Vibration', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Feedback', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Motor', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Console Menu Buttons', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Shoulder Inputs', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Analogue Stick Problems', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => 'Rumble Words', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Screen Time =====
        [
            'title' => 'Screen Time',
            'items' => [
                ['id' => 1, 'text' => 'Story', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Photo', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Spectator', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Performance', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Resolution', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Brightness', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'V-Sync', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Motion Blur', 'group_id' => 'B'],
                ['id' => 9, 'text' => '4:3', 'group_id' => 'C'],
                ['id' => 10, 'text' => '16:9', 'group_id' => 'C'],
                ['id' => 11, 'text' => '21:9', 'group_id' => 'C'],
                ['id' => 12, 'text' => '32:9', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Frame', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Refresh', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Fire', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Drop', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => '___ Mode', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Display Settings', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Aspect Ratios', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Rate', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Fast Travel =====
        [
            'title' => 'Fast Travel',
            'items' => [
                ['id' => 1, 'text' => 'Question Mark', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Chest', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Skull', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Campfire', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Glider', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Grapple', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Mount', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Boat', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Tower', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Outpost', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Collectible', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Side Quest', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Way', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Quest', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Objective', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Bench', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Map Icons', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Ways To Cross A Map', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Open World Chores', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Marker', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Inventory Tetris =====
        [
            'title' => 'Inventory Tetris',
            'items' => [
                ['id' => 1, 'text' => 'Encumbered', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Full', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Cluttered', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Overweight', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Backpack', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Stash', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Chest', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Pouch', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Head', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Chest Piece', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Hands', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Feet', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Weight', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Stack', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Carry', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Time', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Inventory Problems', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Container Types', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Equipment Slots', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Limit', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Ranked Queue =====
        [
            'title' => 'Ranked Queue',
            'items' => [
                ['id' => 1, 'text' => 'Bronze', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Silver', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Gold', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Diamond', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Lobby', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Queue', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Ping', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Elo', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Nice', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Sorry', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Group Up', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Push', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Death', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Ranked', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Custom', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Re', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Competitive Ranks', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Matchmaking Words', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Things Teammates Say', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Match', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Cutscene =====
        [
            'title' => 'Cutscene',
            'items' => [
                ['id' => 1, 'text' => 'Pan', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Zoom', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Fade', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Dolly', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Agree', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Refuse', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Ask', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Lie', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Mash', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Hold', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Dodge', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Parry', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Cut', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Post-Credit', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Opening', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Death', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Cinematic Techniques', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Dialogue Options', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Quick Time Prompts', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => 'Words Before \'Scene\'', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Platinum Run =====
        [
            'title' => 'Platinum Run',
            'items' => [
                ['id' => 1, 'text' => 'Bronze Trophy', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Silver Trophy', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Gold Trophy', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Platinum', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'All Endings', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'No Deaths', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Pacifist', 'group_id' => 'B'],
                ['id' => 8, 'text' => '100%', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Secret', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Hidden', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Missable', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Grindy', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Trophy', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Monster', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Bounty', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Witch', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Trophy Tiers', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Completionist Goals', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Rare Achievements', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Hunter', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Early Access =====
        [
            'title' => 'Early Access',
            'items' => [
                ['id' => 1, 'text' => 'Alpha', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Beta', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Release', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Post-Launch', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Nightly', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Preview', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Stable', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Hotfix', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Crash', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Softlock', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Clipping', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Regression', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Slipped', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Pushed Back', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'TBA', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Indefinite', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Development Stages', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Build Types', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Bug Vocabulary', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => 'Delay Language', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Couch Co-op =====
        [
            'title' => 'Couch Co-op',
            'items' => [
                ['id' => 1, 'text' => 'Split Screen', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Player Two', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Same Screen', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Pass The Pad', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Minigame', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Board', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Buzzer', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Team Round', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Blue Shell', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Friendly Fire', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Stealing Kills', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Screen Peeking', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'One', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Count', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Base', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Choice', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Local Multiplayer Words', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Party Game Staples', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Ways To Lose A Friend', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => 'Player ___', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Sound Design =====
        [
            'title' => 'Sound Design',
            'items' => [
                ['id' => 1, 'text' => 'Master', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Music', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Effects', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Dialogue', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Footstep', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Reload', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Pickup', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Ambience', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Battle Theme', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Main Theme', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Credits', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Boss Theme', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Barks', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Grunts', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Lines', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Casting', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Audio Settings', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Sound Effects', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Music Cues', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => 'Voice Work Terms', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Roll A Character =====
        [
            'title' => 'Roll A Character',
            'items' => [
                ['id' => 1, 'text' => 'Height', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Jaw', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Nose', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Skin Tone', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Warrior', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Mage', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Rogue', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Cleric', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Strength', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Agility', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Intellect', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Vitality', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Glass Cannon', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Tank', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Speed', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Meme', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Appearance Sliders', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Classic Classes', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Core Stats', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Build', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Say Cheese =====
        [
            'title' => 'Say Cheese',
            'items' => [
                ['id' => 1, 'text' => 'Aperture', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Filter', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Depth Of Field', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Tilt', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'First Person', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Third Person', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Top Down', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Isometric', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Capture', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Crop', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Export', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Share', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Field', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Point', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Angle', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Out', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Photo Mode Controls', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Camera Angles', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Screenshot Words', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Of View', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Stat Block =====
        [
            'title' => 'Stat Block',
            'items' => [
                ['id' => 1, 'text' => 'd4', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'd6', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'd20', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'd100', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Slashing', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Piercing', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Fire', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Frost', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Armour', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Crit Chance', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Haste', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Resistance', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Saving', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Dodge', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Loot', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Barrel', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Tabletop Dice', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Damage Types', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Derived Stats', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Roll', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Deck Building =====
        [
            'title' => 'Deck Building',
            'items' => [
                ['id' => 1, 'text' => 'Mulligan', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Curve', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Draw', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Discard', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Hand', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Deck', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Graveyard', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Exile', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Aggro', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Control', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Combo', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Midrange', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Mana', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Energy', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Opportunity', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Sunk', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Card Game Terms', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Card Zones', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Deck Archetypes', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Cost', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Detected =====
        [
            'title' => 'Detected',
            'items' => [
                ['id' => 1, 'text' => 'Unaware', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Suspicious', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Searching', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Alerted', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Silencer', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Smoke', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Distraction', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Disguise', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Footsteps', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Shadow', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Body Found', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Noise', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Stealth', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Steal', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Over', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Road', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Stealth States', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Stealth Tools', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Ways To Be Spotted', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Kill', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Endgame =====
        [
            'title' => 'Endgame',
            'items' => [
                ['id' => 1, 'text' => 'Raid', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Dungeon', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Trial', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'New Game Plus', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Farming', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Rerolling', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Dailies', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Attrition', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Caller', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Add Control', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Runner', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Anchor', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Team', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Save', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Data', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Clean', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Post-Campaign Content', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Grind Vocabulary', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Raid Roles', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Wipe', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Remaster =====
        [
            'title' => 'Remaster',
            'items' => [
                ['id' => 1, 'text' => 'Remake', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Remaster', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Port', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Demake', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Textures', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Lighting', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Load Times', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Controls', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Emulation', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Archive', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Delisted', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Abandonware', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Definitive', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Game Of The Year', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Anniversary', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Complete', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Re-Release Types', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'What Gets Upgraded', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Preservation Words', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Edition', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Season Pass =====
        [
            'title' => 'Season Pass',
            'items' => [
                ['id' => 1, 'text' => 'Battle Pass', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Daily Login', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Shop Rotation', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Event', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Cosmetic', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Bundle', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Currency', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Whale', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Season', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Trial', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Code', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Playlist', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Cosmetics', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Pay', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Read', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Invite', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Live Service Furniture', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Monetisation Words', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Things That Expire', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Only', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== The Backlog =====
        [
            'title' => 'The Backlog',
            'items' => [
                ['id' => 1, 'text' => 'No Time', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Too Long', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Wrong Mood', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Saving It', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Wishlist', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Bundle', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Refund', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Impulse Buy', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Main Story', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Completionist', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Abandoned', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Dropped', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Summer', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Flash', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Fire', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Yard', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Unplayed Game Excuses', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Sale Behaviour', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Ways To Finish', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => 'Words Before \'Sale\'', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Physics Engine =====
        [
            'title' => 'Physics Engine',
            'items' => [
                ['id' => 1, 'text' => 'Ragdoll', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Clipping', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Jitter', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'T-Pose', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Hitbox', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Hurtbox', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Mesh', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Trigger Volume', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Bunny Hop', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Wall Jump', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Air Dash', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Slide Cancel', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Cloth', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Rag', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Water', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Rocket', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Physics Bugs', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Collision Words', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Movement Tech', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Physics', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Modding =====
        [
            'title' => 'Modding',
            'items' => [
                ['id' => 1, 'text' => 'Texture Pack', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Total Conversion', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Quality Of Life', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Cosmetic Mod', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Loader', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Manager', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Script Extender', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Patcher', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Nexus', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Workshop', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Forum', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Discord', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Graphics', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Combat', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'UI', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Balance', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Mod Types', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Mod Tools', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Community Sites', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Overhaul', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Insert Coin =====
        [
            'title' => 'Insert Coin',
            'items' => [
                ['id' => 1, 'text' => 'Marquee', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Joystick', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Coin Slot', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Attract Mode', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'High Score', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Continue?', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Three Lives', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Initials', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Clamshell', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Cartridge', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Backlight', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Link Cable', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'High', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Metacritic', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Box', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Under', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Arcade Cabinet Words', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Arcade Era Concepts', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Handheld Hardware', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Score', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Ding =====
        [
            'title' => 'Ding',
            'items' => [
                ['id' => 1, 'text' => 'XP', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Skill Tree', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Prestige', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Respec', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Upgrade', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Enchant', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Ascend', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Unlock', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Level Gate', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Paywall', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Key Item', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Reputation', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Level', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Frame', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Hand', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Salary', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Progression Systems', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Ways To Get Stronger', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Soft Locks On Progress', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Cap', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Netcode =====
        [
            'title' => 'Netcode',
            'items' => [
                ['id' => 1, 'text' => 'Lag', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Packet Loss', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Rubber-Banding', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Desync', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Rollback', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Delay', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Peer To Peer', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Dedicated', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Region', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Tick Rate', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Downtime', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Queue Position', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Idle Player', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Cheater', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Host', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Whole Lobby', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Connection Problems', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Netcode Approaches', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Server Words', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => 'Things That Get Kicked', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Minigame =====
        [
            'title' => 'Minigame',
            'items' => [
                ['id' => 1, 'text' => 'Fishing', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Lockpicking', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Hacking', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Card Game', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Chart', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Note', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Combo', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Timing', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Sliding', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Sokoban', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Match Three', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Logic Grid', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Finish', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Story', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Time', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Punch', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Recurring Minigames', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Rhythm Game Words', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Puzzle Types', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Line', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== End Credits =====
        [
            'title' => 'End Credits',
            'items' => [
                ['id' => 1, 'text' => 'Design', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Programming', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Art', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Special Thanks', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Teaser', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Bonus Boss', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Thank You Note', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Sequel Hook', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'QA', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Audio', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Narrative', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Production', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Dev', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Red', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Home', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Dream', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Credits Roll Sections', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Post-Credits Content', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Studio Departments', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Team', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Tutorial Island =====
        [
            'title' => 'Tutorial Island',
            'items' => [
                ['id' => 1, 'text' => 'Pop-Up', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Ghost Input', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Training Room', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Helpful NPC', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Walk', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Jump', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Fight', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Die', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Too Long', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Unskippable', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Patronising', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Too Late', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Strategy', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Field', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Trophy', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Tour', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Tutorial Devices', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'First Hour Beats', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Onboarding Complaints', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Guide', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Game Feel =====
        [
            'title' => 'Game Feel',
            'items' => [
                ['id' => 1, 'text' => 'Screen Shake', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Hit Stop', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Particles', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Rumble', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Wind-Up', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Recovery', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Follow-Through', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Blend', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Snappy', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Floaty', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Weighty', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Sluggish', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Parry', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Cancel', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Launch', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Overton', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Juice And Feedback', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Animation Terms', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Words For Responsiveness', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Window', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Options Menu =====
        [
            'title' => 'Options Menu',
            'items' => [
                ['id' => 1, 'text' => 'Subtitles', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Colourblind Mode', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Remapping', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Aim Assist', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Motion Sickness', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Camera Shake', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Flashing Lights', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Text Size', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Slow Motion', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Invincibility', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Auto Aim', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Skip Puzzle', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'On', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Off', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Auto', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Custom', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Accessibility Settings', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Comfort Settings', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Assist Features', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => 'Toggle States', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Build A PC =====
        [
            'title' => 'Build A PC',
            'items' => [
                ['id' => 1, 'text' => 'GPU', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'CPU', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'RAM', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'SSD', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Bottleneck', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Overclock', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Thermals', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Benchmark', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'DLSS', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'FSR', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'XeSS', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'TAA', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Graphics', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Audio', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Privacy', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Unreal', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'PC Components', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Performance Words', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Upscaling Tech', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Settings', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Storefront =====
        [
            'title' => 'Storefront',
            'items' => [
                ['id' => 1, 'text' => 'Steam', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Epic', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'GOG', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Itch', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Screenshots', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Reviews', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Requirements', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Tags', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Overwhelming', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Mostly Positive', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Mixed', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Negative', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Product', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Skeleton', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Low', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Answer', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'PC Storefronts', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Store Page Sections', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Review Verdicts', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Key', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
        // ===== Genre Blend =====
        [
            'title' => 'Genre Blend',
            'items' => [
                ['id' => 1, 'text' => 'Action-RPG', 'group_id' => 'A'],
                ['id' => 2, 'text' => 'Puzzle-Platformer', 'group_id' => 'A'],
                ['id' => 3, 'text' => 'Deck-Builder', 'group_id' => 'A'],
                ['id' => 4, 'text' => 'Life-Sim', 'group_id' => 'A'],
                ['id' => 5, 'text' => 'Farming', 'group_id' => 'B'],
                ['id' => 6, 'text' => 'Driving', 'group_id' => 'B'],
                ['id' => 7, 'text' => 'Flight', 'group_id' => 'B'],
                ['id' => 8, 'text' => 'Cooking', 'group_id' => 'B'],
                ['id' => 9, 'text' => 'Survival', 'group_id' => 'C'],
                ['id' => 10, 'text' => 'Psychological', 'group_id' => 'C'],
                ['id' => 11, 'text' => 'Cosmic', 'group_id' => 'C'],
                ['id' => 12, 'text' => 'Found Footage', 'group_id' => 'C'],
                ['id' => 13, 'text' => 'Physics', 'group_id' => 'D'],
                ['id' => 14, 'text' => 'Creative', 'group_id' => 'D'],
                ['id' => 15, 'text' => 'Social', 'group_id' => 'D'],
                ['id' => 16, 'text' => 'Litter', 'group_id' => 'D'],
            ],
            'groups' => [
                ['id' => 'A', 'name' => 'Hyphenated Genres', 'tier' => 1, 'color' => 'green'],
                ['id' => 'B', 'name' => 'Sim Subjects', 'tier' => 2, 'color' => 'blue'],
                ['id' => 'C', 'name' => 'Horror Flavours', 'tier' => 3, 'color' => 'purple'],
                ['id' => 'D', 'name' => '___ Sandbox', 'tier' => 4, 'color' => 'gold'],
            ],
        ],
    ];
}

/*
 * To put this batch into rotation, add to tag_connections_get_puzzle_pool():
 *
 *     require_once __DIR__ . '/puzzle-content-batch2.php';
 *     return array_merge($pool, tag_connections_get_puzzle_pool_batch2());
 *
 * Appending rather than interleaving is fine: the scheduler no longer walks the
 * pool in order, it picks by franchise and genre spacing, so where these sit in
 * the array does not decide when they play.
 */
